### PR TITLE
fix: bump js-yaml to 3.13.1

### PR DESCRIPTION
**Pull request by rajivshah3**
- [x] Ready for review
- [x] Follows CONTRIBUTING rules
- [ ] Reviewed by Snyk internal team

#### What does this PR do?
Bumps `js-yaml` to 3.13.1 to fix a [vulnerability](https://app.snyk.io/vuln/SNYK-JS-JSYAML-174129)

#### Where should the reviewer start?
N/A

#### How should this be manually tested?
N/A

#### Any background context you want to provide?
N/A

#### What are the relevant tickets?
N/A

#### Screenshots
N/A

#### Additional questions
N/A

### CODE REVIEW

**Comment by darmalovan** [comment]
Hello, this update went out on https://github.com/snyk/policy/pull/28/

**Comment by rajivshah3** [comment]
It looks like #28 updated it to 3.13.0. According to [Snyk](https://app.snyk.io/vuln/SNYK-JS-JSYAML-174129) it needs to be updated to 3.13.1 to fix another issue

**Comment by darmalovan** [comment]
Hey @rajivshah3 
It was updated to `^3.13.0` which is equivalent. 
If you tested it by the CLI you should verify you have fresh `node_modules`

**Comment by rajivshah3** [comment]
Ah whoops, looks like my yarn.lock was still specifying 3.13.0. Sorry about that!

**Pull request closed without merging**
