### PR TITLE
chore: pin semantic-release version for node 18 support

### PR DESCRIPTION
**Pull request by agatakrajewska**
- [ ] Ready for review
- [ ] Follows CONTRIBUTING rules
- [ ] Reviewed by Snyk internal team

#### What does this PR do?
We're pinning the `semantic-release` version to `22.0.0` for the `node18` support. 

Dropping EOL `node16`.

### CODE REVIEW

**Review by gclapperton — APPROVED** [review]

**Comment by gclapperton** [comment]
Dropping support for Node 16 is arguably a breaking change

**Comment by agatakrajewska** [comment]
> Dropping support for Node 16 is arguably a breaking change

Yes absolutely! That is why I have marked it as a `feat` commit, as I understand you can do that or alternatively add a `BREAKING CHANGE` keyword to the commit. Do you think `feat` is not sufficient?

**Comment by agatakrajewska** [comment]
> > Dropping support for Node 16 is arguably a breaking change
> 
> Yes absolutely! That is why I have marked it as a `feat` commit, as I understand you can do that or alternatively add a `BREAKING CHANGE` keyword to the commit. Do you think `feat` is not sufficient?

I see, I need both. Updated!

**Pull request merged**
